[ACS-777] Email notification for digital workspace
Alfresco/rest-api-explorer pull request #108
Opened 2020-11-03 07:17 UTC by dhrn

REST APIs that send email to use an optional client name. The client name is used to lookup the custom email template and its related assets based on the registered configuration.

https://alfresco.atlassian.net/browse/ACS-777

2020-11-05 08:40 UTC, alandavis reviewed
Given that I think there may need to be some restrictions on what may be included in these parameters (possibly no links to external systems or relative paths), you may need to add to these descriptions and exit codes if the values are invalid.

2020-11-05 08:40 UTC, alandavis commented on src/main/webapp/definitions/alfresco-core.yaml
> +            Optionally provided in the request query to customise the sent email.
Should read "email sent" not "sent email". Also on line 4329

2020-11-05 09:02 UTC, gavincornwell requested changes

2020-11-05 09:02 UTC, gavincornwell commented on src/main/webapp/definitions/alfresco-core.yaml
> +          in: query
I'm afraid this is not the correct approach, for POST APIs the body should be used to send values to the API, the query parameters are only supposed to be used for controlling the response i.e. paging, fields etc.

To send in extra data you should be updating the "siteMembershipRequestBodyCreate" body definition with new additional properties i.e. "client" and "workspacePath"

2020-11-05 09:02 UTC, gavincornwell commented on src/main/webapp/definitions/alfresco-core.yaml
> +          in: query
Same comment as above, should be in the body.

2020-11-05 09:02 UTC, gavincornwell commented on src/main/webapp/definitions/alfresco-core.yaml
> +            Optionally override the workspace deployment links to customise the sent email.
I don't think this is descriptive enough, it's not clear to me what effect this parameter has. If it's a URL we'll need to be extra careful we don't open security issues.

2020-11-05 16:44 UTC, eromano approved these changes

2020-11-05 17:17 UTC, gavincornwell requested changes
Thank you for the update,  a couple of additional minor comments.

2020-11-05 17:17 UTC, gavincornwell commented on src/main/webapp/definitions/alfresco-core.yaml
> +          Optionally provided in the request query to customise the email sent.
I would change this to something like:
Optional client name used when sending an email to the end user, defaults to "share" if not provided.

Presuming "share" is the default ;-) Replace as necessary.

2020-11-06 12:29 UTC, gavincornwell approved these changes
LGTM

2020-11-16 09:24 UTC, merged