Feature/ACS-937 migrate swagger UI to v3
Alfresco/rest-api-explorer pull request #118
Opened 2021-01-04 17:40 UTC by andrea-ligios

2021-01-04 17:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/rest-api-explorer?pullRequest=118) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/rest-api-explorer?pullRequest=118) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/rest-api-explorer?pullRequest=118) it.</sub>

2021-01-05 09:50 UTC, mauriziovitale approved these changes

2021-01-05 09:51 UTC, mauriziovitale commented
> Hi @andrea-ligios if you could add some description also for future memory thanks

Do you mean doc?

2021-01-05 10:02 UTC, gavincornwell requested changes
Awesome job @andrea-ligios!

I ran the API Explorer locally and had a quick look, on the whole it works great, however, I did find the following error when expanding the POST /search endpoint.

<img width="1786" alt="Screenshot 2021-01-05 at 09 56 38" src="https://user-images.githubusercontent.com/1194868/103632996-05923780-4f3d-11eb-92c2-bb81f4b7045e.png">

2021-01-05 10:55 UTC, eromano commented
> > Hi @andrea-ligios if you could add some description also for future memory thanks
> 
> Do you mean doc?

I mean here in the PR:
No description provided.

2021-01-13 08:32 UTC, andrea-ligios commented
@gavincornwell it's likely a [Swagger UI 3 issue](https://stackoverflow.com/q/65584131/1654265), nothing we should be able to address:

![image](https://user-images.githubusercontent.com/11974750/104425581-22ec8480-5581-11eb-94c3-66e65f14fd6f.png)

If you agree and approve the PR, we can merge.

2021-01-13 09:36 UTC, gavincornwell commented
@andrea-ligios Thanks for investigating and digging deeper, we have indeed had to live with bugs in the older version too.

However, this one is quite prominent :-( Is it actually still possible to use the "Try it Out" button despite the error? The response mentions circular references, have you done a quick check of our definition?

2021-01-13 13:22 UTC, andrea-ligios commented
> @andrea-ligios Thanks for investigating and digging deeper, we have indeed had to live with bugs in the older version too.
> 
> However, this one is quite prominent :-( Is it actually still possible to use the "Try it Out" button despite the error? The response mentions circular references, have you done a quick check of our definition?

It is possible to use the "Try it Out" button, and I've not found any problem in the API definition.
The `pivot` element is just rendered differently than before (`null` instead of`{}`) 

Swagger UI 2:
![image](https://user-images.githubusercontent.com/11974750/104457633-96ef5280-55aa-11eb-9b1b-75c58883ac4d.png)

Swagger UI 3:
![image](https://user-images.githubusercontent.com/11974750/104457657-a078ba80-55aa-11eb-9e32-f86dcbd98742.png)

In either case, it needs to get populated properly before being passed as a parameter, so I'm going to document this error in the API definition and then wait for your final review to merge the PR.

2021-01-14 08:52 UTC, gavincornwell approved these changes
LGTM, presuming the warning about the error in the search API is moved to the start of the description.

2021-01-14 08:52 UTC, gavincornwell commented on src/main/webapp/definitions/alfresco-search.yaml
> +        **Note**: after the migration to Swagger UI 3, this API definition is raising **two errors on the top of this page**, related to the `pivots` field.
This is great, but personally, I would put this right at the beginning of the description so it's the first thing the user reads.

2021-01-14 09:17 UTC, merged