[REPO-5552] more filtering capablities for aspect/type api
Alfresco/rest-api-explorer pull request #125
Opened 2021-02-16 08:47 UTC by dhrn

Following the capability added to aspect/type api

* include properties
* INCLUDESUBTYPES
* INCLUDESUBASPECTS
* typo fixed

2021-02-16 10:24 UTC, skopf approved these changes
So you are making properties an optional feature, right? Makes sense. Sometimes, we just need the basic information about types/aspects to render a UI but we do not need all the details.
If you are already looking at making property definitions optional, you should also look at associations for types. They are typically not required in many cases and should also be optional.

2021-02-16 10:25 UTC, skopf requested changes
So you are making properties an optional feature, right? Makes sense. Sometimes, we just need the basic information about types/aspects to render a UI but we do not need all the details.
If you are already looking at making property definitions optional, you should also look at associations for types. They are typically not required in many cases and should also be optional.
But we cannot make them optional in a later version of this API. So we should include this in this first revision.

2021-02-16 18:30 UTC, skopf commented
The confluence page does not correctly describe the layout we need for associations. We actually need:
```
id -> getName()
title ->  getTitle()
description -> getDescription()
child -> isChild
protected -> isProtected()
```
plus two JSON child objects for `source`and `target` with these properties  each
```
role -> get[ST]RoleName()
cls -> get[ST]Class()
many -> is[Source|Target]Many()
mandatory -> is[Source|Target]Mandatory()
mandatoryEnforced -> is[Source|Target]MandatoryEnforced()
```

2021-02-17 11:30 UTC, gavincornwell requested changes

2021-02-17 11:30 UTC, gavincornwell commented on src/main/webapp/definitions/alfresco-model.yaml
> +            * container
We typically use the include mechanism for data that could be expensive to retrieve or make the response very large, properties, associations and mandatoryAspects are good examples of this. 

Personally I would just have boolean properties in the response by default.

2021-02-17 11:30 UTC, gavincornwell commented on src/main/webapp/definitions/alfresco-model.yaml
> +      many:
Boolean properties should be prefixed with "is" according to the guidelines.

2021-02-17 12:56 UTC, gavincornwell approved these changes
LGTM

2021-02-22 08:24 UTC, skopf approved these changes
LGTM

2021-02-23 09:56 UTC, eromano approved these changes
LGTM thanks @dhrn

2021-02-23 09:56 UTC, merged